### ISSUE TITLE
support nette/DI 3.1.0

### ISSUE THREAD

**Issue by qwerin** [contributte/elasticsearch#19]
only update composer.json?

**Comment by f3l1x** [comment]
https://github.com/contributte/elasticsearch/commit/c1c35101dbabdc2d645d303f29e3cde882985002

**Comment by bartko-s** [comment]
@f3l1x  @vojtechmares  - bolo by mozne vydat novu verziu. Lebo aktualna ma podmienku `"nette/di": "~3.0.1"` Najnovsia verzia ma `"nette/di": "^3.0.1"` cize uz sa nainstaluje verzia 3.1.8 ktora podporuje php8.2+
Dakujem

**Comment by f3l1x** [comment]
Done https://github.com/contributte/elasticsearch/releases/tag/v0.5.0

**Comment by f3l1x** [comment]
Pro jistotu jeste tady https://github.com/contributte/elasticsearch/releases/tag/v0.4.2
