### ISSUE TITLE
Refactoring: internal changes

### ISSUE THREAD

**Issue by f3l1x** [contributte/elasticsearch#2]
- drop monolog dependency
- drop kdyby/monolog suggestion (well..)
- raise to PHP 7.1
- change rules to `vendor/ninjify/coding-standard/contributte.xml`
- update LINCENSE
- travis.yml is invalid (duplicate)

**Comment by vojtechmares** [comment]
`monolog/monolog` must stay as dev dependency, see https://travis-ci.org/contributte/elasticsearch/jobs/385596572
